on:
  push:
    branches: [update_deploy_action]

name: rebuild_slides

jobs:
  build_slides:
    runs-on: ubuntu-latest
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-renv@v1
      
      - name: Install system dependencies
        run: sudo /bin/sh system_requirements.sh

      - name: Cache icons
        uses: actions/cache@v2
        with:
          path: ~/.local/share/rpkg_icon
          key: ${{ runner.os }}-icons-1

      - name: Download icons
        run: |
          library(icons)

          # make sure the icons are downloaded
          if (!icon_installed(fontawesome)) {
            download_fontawesome()
          }
        shell: Rscript {0}
        
      - name: Cache rendered html files
        uses: actions/cache@v2
        with:
          path: ~/*.html
          key: ${{ runner.os }}-html-1
          
      - name: Build slides
        run: |
          git config --local user.email "nhs.rcommunity@nhs.net"
          git config --local user.name "NHS-R Community"
          make all
          
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages-test
          folder: public